[package]
name = "xiny"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
clap_complete = "4.5.33"
crossterm = "0.28.1"
dirs = "5.0.1"
phf = { version = "0.11.2", features = ["macros"] }
regex = "1.11.0"
term_size = "0.3.2"
