[package]
name = "xiny"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
clap_complete = "4.5.33"
dirs = "5.0.1"
lazy_static = "1.5.0"
regex = "1.11.0"
skim = "0.10.4"
